# -*- coding: utf-8 -*-
"""preprocessing (reports..audio).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sm5Yhm1SD2RoSR_4mNu3CbH6z5PwCqQQ
"""

!pip install openai-whisper
!pip install pandas nltk deep-translator

!import nltk
nltk.download('punkt_tab')

import os
import pandas as pd
import whisper
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from deep_translator import GoogleTranslator

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Set audio file path
audio_file = "/content/harvard.wav"  # Your single audio file
output_csv = "/content/audio_transcription.csv"

# Load Whisper model
model = whisper.load_model("base")

# Transcribe and translate
print(f"Transcribing: {audio_file}")
result = model.transcribe(audio_file)
text = result['text']

# Translate if needed
try:
    translated_text = GoogleTranslator(source='auto', target='en').translate(text)
except Exception as e:
    print(f"Translation failed: {e}")
    translated_text = text

# Save raw transcription
df = pd.DataFrame([{"filename": os.path.basename(audio_file), "transcription": translated_text}])
df.to_csv(output_csv, index=False)
print(f"Transcription saved to: {output_csv}")

# Preprocess the transcription
def preprocess_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = nltk.word_tokenize(text)
    tokens = [t for t in tokens if t not in stopwords.words('english')]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

df['processed_text'] = df['transcription'].apply(preprocess_text)

# Save preprocessed text
preprocessed_csv = "/content/preprocessed_audio_transcription.csv"
df.to_csv(preprocessed_csv, index=False)
print(f"Preprocessed transcription saved to: {preprocessed_csv}")

import os
import zipfile
import pandas as pd
import whisper
import nltk
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from deep_translator import GoogleTranslator

# Download required NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# === Step 1: Extract ZIP ===
zip_path = "/content/archive.zip"
extract_to = "/content/extracted_audio"

os.makedirs(extract_to, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print(f"Extracted audio files to: {extract_to}")

# === Step 2: Transcribe and Translate ===
model = whisper.load_model("base")  # or "tiny" for lower RAM usage
transcriptions = []

for file in os.listdir(extract_to):
    if file.lower().endswith(('.mp3', '.wav', '.m4a')):
        file_path = os.path.join(extract_to, file)
        print(f"Transcribing: {file}")
        try:
            result = model.transcribe(file_path)
            text = result['text']
            # Translate to English
            try:
                translated = GoogleTranslator(source='auto', target='en').translate(text)
            except Exception as e:
                print(f"Translation failed: {e}")
                translated = text
            transcriptions.append({
                "filename": file,
                "transcription": translated
            })
        except Exception as e:
            print(f"Transcription failed for {file}: {e}")

# Save to CSV
df = pd.DataFrame(transcriptions)
raw_csv_path = "/content/audio_transcriptions.csv"
df.to_csv(raw_csv_path, index=False)
print(f"Transcriptions saved to: {raw_csv_path}")

# === Step 3: Preprocessing ===
def preprocess_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    tokens = nltk.word_tokenize(text)
    tokens = [t for t in tokens if t not in stopwords.words('english')]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)

df['processed_text'] = df['transcription'].apply(preprocess_text)

# Save preprocessed version
processed_csv_path = "/content/preprocessed_audio_transcriptions.csv"
df.to_csv(processed_csv_path, index=False)
print(f"Preprocessed transcriptions saved to: {processed_csv_path}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Flatten, Bidirectional, GlobalAveragePooling1D, Reshape

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

# Load preprocessed data
df = pd.read_csv("/content/preprocessed_audio_transcriptions.csv")

# Dummy labels (You should replace this with actual audio class if you have any)
df['label'] = np.random.choice(['class1', 'class2'], size=len(df))  # Random labels for demo

# Encode labels
label_encoder = LabelEncoder()
df['label_encoded'] = label_encoder.fit_transform(df['label'])

# Tokenize
tokenizer = Tokenizer(num_words=5000, oov_token='<OOV>')
tokenizer.fit_on_texts(df['processed_text'])
sequences = tokenizer.texts_to_sequences(df['processed_text'])
padded_sequences = pad_sequences(sequences, maxlen=100, padding='post')

X = padded_sequences
y = df['label_encoded'].values

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from wordcloud import WordCloud

# Word cloud
text_all = ' '.join(df['processed_text'])
wordcloud = WordCloud(width=800, height=400).generate(text_all)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud of Audio Transcripts")
plt.show()

# Label distribution
plt.figure(figsize=(6, 4))
sns.countplot(x='label', data=df)
plt.title("Label Distribution")
plt.show()

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Embedding, Conv1D, MaxPooling1D, Flatten, GlobalAveragePooling1D, Bidirectional, LSTM, Input, Lambda
from transformers import TFDistilBertModel, DistilBertTokenizer
from sklearn.model_selection import train_test_split # Make sure this is imported
from sklearn.metrics import accuracy_score # Make sure this is imported
import pandas as pd # Make sure pandas is imported as df is used

df = pd.read_csv("/content/preprocessed_audio_transcriptions.csv")

if 'label' not in df.columns:
    df['label'] = np.random.choice(['class1', 'class2'], size=len(df))  # Random labels for demo

# Encode labels
if 'label_encoded' not in df.columns:
    from sklearn.preprocessing import LabelEncoder
    label_encoder = LabelEncoder()
    df['label_encoded'] = label_encoder.fit_transform(df['label'])

# Assuming tokenizer and padded_sequences are available. Re-create if necessary.
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000, oov_token='<OOV>')
tokenizer.fit_on_texts(df['processed_text'])
sequences = tokenizer.texts_to_sequences(df['processed_text'])
# Padded sequences for CNN/RNN (length 100 as before)
padded_sequences = pad_sequences(sequences, maxlen=100, padding='post')


train_indices, test_indices = train_test_split(df.index, test_size=0.2, random_state=42)
X_train_text = df.loc[train_indices, 'processed_text']
y_train = df.loc[train_indices, 'label_encoded'].values

X_test_text = df.loc[test_indices, 'processed_text']
y_test = df.loc[test_indices, 'label_encoded'].values

# Also get the padded sequences for the CNN/RNN models using these indices
X_train_padded = padded_sequences[train_indices]
X_test_padded = padded_sequences[test_indices]


# CNN Model (Use X_train_padded and X_test_padded)
cnn_model = Sequential([
    Embedding(input_dim=5000, output_dim=64, input_length=100),
    Conv1D(128, 5, activation='relu'),
    MaxPooling1D(pool_size=2),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(len(np.unique(df['label_encoded'])), activation='softmax')
])
cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
print("Training CNN model...")
cnn_model.fit(X_train_padded, y_train, epochs=5, validation_data=(X_test_padded, y_test), verbose=1)

cnn_pred = np.argmax(cnn_model.predict(X_test_padded), axis=1)
cnn_acc = accuracy_score(y_test, cnn_pred)


# RNN Model (Use X_train_padded and X_test_padded)
rnn_model = Sequential([
    Embedding(5000, 64, input_length=100),
    Bidirectional(LSTM(64)),
    Dense(64, activation='relu'),

    Dense(len(np.unique(df['label_encoded'])), activation='softmax')
])
rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
print("\nTraining RNN model...")
rnn_model.fit(X_train_padded, y_train, epochs=5, validation_data=(X_test_padded, y_test), verbose=1)

rnn_pred = np.argmax(rnn_model.predict(X_test_padded), axis=1)
rnn_acc = accuracy_score(y_test, rnn_pred)


# Transformer Model with DistilBERT
bert_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

def bert_encode(texts, max_len=128):
    # Change padding=True to padding='max_length'
    return bert_tokenizer(texts.tolist(), padding='max_length', truncation=True, max_length=max_len, return_tensors='tf')

# Use the text Series directly for encoding
train_encodings = bert_encode(X_train_text)
test_encodings = bert_encode(X_test_text)

bert_model = TFDistilBertModel.from_pretrained("distilbert-base-uncased")

# Define model inputs (Shapes match the bert_encode max_len)
input_ids = Input(shape=(128,), dtype=tf.int32, name="input_ids")
attention_mask = Input(shape=(128,), dtype=tf.int32, name="attention_mask")

# The Lambda layer expects input with shapes matching the Input layers
# Add output_shape argument to Lambda layer
embedding = Lambda(lambda inputs: bert_model(inputs[0], attention_mask=inputs[1])[0], output_shape=(128, 768))([input_ids, attention_mask])


x = GlobalAveragePooling1D()(embedding)
x = Dense(64, activation='relu')(x)

output = Dense(len(np.unique(df['label_encoded'])), activation='softmax')(x)

transformer_model = Model(inputs=[input_ids, attention_mask], outputs=output)
transformer_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("\nTraining Transformer model...")
transformer_model.fit(
    {'input_ids': train_encodings['input_ids'], 'attention_mask': train_encodings['attention_mask']},
    y_train,
    validation_data=(
        {'input_ids': test_encodings['input_ids'], 'attention_mask': test_encodings['attention_mask']},
        y_test
    ),
    epochs=3,
    batch_size=8 # Reduce batch size if memory is an issue
)

transformer_pred = np.argmax(transformer_model.predict({
    'input_ids': test_encodings['input_ids'],
    'attention_mask': test_encodings['attention_mask']
}), axis=1)
transformer_acc = accuracy_score(y_test, transformer_pred)

model_names = ['CNN', 'RNN', 'Transformer']
accuracies = [cnn_acc, rnn_acc, transformer_acc]

plt.figure(figsize=(6, 4))
sns.barplot(x=model_names, y=accuracies)
plt.ylim(0, 1)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

print(f"CNN Accuracy:        {cnn_acc:.4f}")
print(f"RNN (LSTM) Accuracy: {rnn_acc:.4f}")
print(f"Transformer Accuracy:{transformer_acc:.4f}")

