# -*- coding: utf-8 -*-
"""preprocessing (reports..images)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq8O9BVY5dON0bZCcaWk79ybhbhinsam
"""

!pip install nltk

import nltk

nltk.download('maxent_ne_chunker_tab')

# Ensure PyMuPDF is installed correctly
!pip install --upgrade PyMuPDF

import zipfile
import os

# Define paths
zip_path = "/content/data.zip"
extract_to = "/content/temp_extracted_pdfs"
target_subdir = os.path.join(extract_to, "data")

# Create target directory if it doesn't exist
os.makedirs(target_subdir, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(target_subdir)

print(f" Extracted '{zip_path}' to '{target_subdir}'")

import fitz  # PyMuPDF
import os
import cv2
import numpy as np

# Input and output directories
pdf_folder = "/content/temp_extracted_pdfs/data/data"
output_dir = "extracted_images"
preprocessed_dir = "preprocessed_images"

# Create output directories if they don't exist
os.makedirs(output_dir, exist_ok=True)
os.makedirs(preprocessed_dir, exist_ok=True)

def preprocess_image(image_path, output_path):
    # Load image
    image = cv2.imread(image_path)

    if image is None:
        print(f"Warning: Unable to read image {image_path}")
        return

    # Resize to fixed size
    image = cv2.resize(image, (224, 224))

    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply Gaussian blur
    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    # Apply adaptive thresholding
    thresh = cv2.adaptiveThreshold(
        blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY, 11, 2
    )

    # Save the processed image
    cv2.imwrite(output_path, thresh)

# Process each PDF in the folder
total_img_count = 0

for pdf_file in os.listdir(pdf_folder):
    if pdf_file.endswith(".pdf"):
        pdf_path = os.path.join(pdf_folder, pdf_file)
        doc = fitz.open(pdf_path)
        pdf_name = os.path.splitext(pdf_file)[0]

        for page_index in range(len(doc)):
            page = doc[page_index]
            images = page.get_images(full=True)

            for img_index, img in enumerate(images):
                xref = img[0]
                base_image = doc.extract_image(xref)
                image_bytes = base_image["image"]
                image_ext = base_image["ext"]
                image_filename = f"{pdf_name}_page{page_index+1}_img{img_index+1}.{image_ext}"
                image_path = os.path.join(output_dir, image_filename)

                # Save extracted image
                with open(image_path, "wb") as f:
                    f.write(image_bytes)

                # Preprocess and save
                preprocessed_path = os.path.join(preprocessed_dir, image_filename)
                preprocess_image(image_path, preprocessed_path)

                total_img_count += 1

print(f" Extracted and preprocessed {total_img_count} images from PDFs in '{pdf_folder}'.")
print(f" Extracted images saved in '{output_dir}'")
print(f" Preprocessed images saved in '{preprocessed_dir}'")

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.impute import SimpleImputer
from imblearn.combine import SMOTEENN
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Reshape
from tensorflow.keras.callbacks import EarlyStopping

# Set path and limits
image_path = "/content/preprocessed_images"
max_images = 500  # Limit images for Colab safety
image_size = (64, 64)  # Resize to reduce memory

# Load and resize grayscale images
images = []
labels_placeholder = []
for i, img_file in enumerate(os.listdir(image_path)):
    if i >= max_images:
        break
    img_full_path = os.path.join(image_path, img_file)
    img = cv2.imread(img_full_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        img_resized = cv2.resize(img, image_size)
        images.append(img_resized.astype(np.float32))  # use float32 for efficiency
        labels_placeholder.append(i % 5)  # Dummy labels for clustering (replace with actual if available)

images = np.array(images)
if images.size == 0:
    print("No images found.")
else:
    print(f"Loaded {len(images)} images with shape {images.shape}")

    # Flatten and clean
    flat_images = images.reshape(len(images), -1)
    imputer = SimpleImputer(strategy='mean')
    cleaned_data = imputer.fit_transform(flat_images)

    # KMeans clustering
    kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
    labels = kmeans.fit_predict(cleaned_data)

    # Remove single-instance clusters
    unique_labels, counts = np.unique(labels, return_counts=True)
    valid_clusters = unique_labels[counts > 1]
    mask = np.isin(labels, valid_clusters)
    cleaned_data = cleaned_data[mask]
    labels = labels[mask]

    if len(cleaned_data) == 0:
        print("No data left after filtering.")
    else:
        # Dimensionality reduction
        pca = PCA(n_components=30)
        reduced_data = pca.fit_transform(cleaned_data)

        # Scaling
        scaler = MinMaxScaler()
        scaled_data = scaler.fit_transform(reduced_data)

        # Hybrid oversampling
        sampler = SMOTEENN(random_state=42)
        oversampled_data, oversampled_labels = sampler.fit_resample(scaled_data, labels)

        # Visualization
        plt.figure(figsize=(6, 4))
        sns.histplot(oversampled_data[:, 0], kde=True)
        plt.title("Feature 1 Distribution")
        plt.tight_layout()
        plt.show()

        # Train/test split
        X_train, X_test, y_train, y_test = train_test_split(
            oversampled_data, oversampled_labels, test_size=0.2, random_state=42
        )

        early_stop = EarlyStopping(monitor='loss', patience=3, restore_best_weights=True)

        # Dense model (formerly CNN)
        cnn_model = Sequential([
            Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
            Dense(32, activation='relu'),
            Dense(len(np.unique(y_train)), activation='softmax')
        ])
        cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

        print("Training Dense model...")
        cnn_model.fit(X_train, y_train, epochs=10, batch_size=16, callbacks=[early_stop], verbose=1)

        # RNN model
        rnn_model = Sequential([
            Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),
            LSTM(32, return_sequences=False),
            Dense(16, activation='relu'),
            Dense(len(np.unique(y_train)), activation='softmax')
        ])
        rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

        print("Training RNN model...")
        rnn_model.fit(X_train, y_train, epochs=10, batch_size=16, callbacks=[early_stop], verbose=1)

        # Evaluation
        print("\nEvaluating models...")
        cnn_loss, cnn_acc = cnn_model.evaluate(X_test, y_test, verbose=0)
        rnn_loss, rnn_acc = rnn_model.evaluate(X_test, y_test, verbose=0)

        print(f"Dense Model Accuracy: {cnn_acc:.4f}")
        print(f"RNN Model Accuracy: {rnn_acc:.4f}")

        # Save outputs
        np.save("/content/cleaned_images_data.npy", oversampled_data)
        np.save("/content/oversampled_image_labels.npy", oversampled_labels)

