# -*- coding: utf-8 -*-
"""preprocessing (reports..texts)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDgzVyATsT0UV6EnU4y0YbatOZVQzBJn
"""

!pip install nltk

import nltk

nltk.download('maxent_ne_chunker_tab')

# Ensure PyMuPDF is installed correctly
!pip install --upgrade PyMuPDF

# Ensure PyMuPDF is installed correctly
!pip install --upgrade --force-reinstall PyMuPDF

!pip install --upgrade --force-reinstall PyMuPDF

!pip install fpdf

!pip install PyMuPDF pandas

import zipfile
import os

# Define paths
zip_path = "/content/data.zip"
extract_to = "/content/temp_extracted_pdfs"
target_subdir = os.path.join(extract_to, "data")

# Create target directory if it doesn't exist
os.makedirs(target_subdir, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(target_subdir)

print(f" Extracted '{zip_path}' to '{target_subdir}'")

import os
import fitz  # PyMuPDF
import re
import pandas as pd


def extract_text_from_pdf(pdf_path):
    """Extract text from all pages of the PDF"""
    doc = fitz.open(pdf_path)
    full_text = []

    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        text = page.get_text()
        full_text.append(text)

    doc.close()
    return full_text


def clean_text(text):
    """Clean extracted text by removing unwanted characters and multiple spaces"""
    text = re.sub(r'\s+', ' ', text)  # collapse multiple whitespace
    text = re.sub(r'[^A-Za-z0-9.,:%()\-/& ]', '', text)  # retain only meaningful chars
    return text.strip()


def process_pdf_folder(input_folder, output_csv):
    """Process all PDF files in a folder and save results to one CSV"""
    all_data = []

    for filename in os.listdir(input_folder):
        if filename.lower().endswith(".pdf"):
            file_path = os.path.join(input_folder, filename)
            print(f"Processing {filename}...")

            try:
                raw_text = extract_text_from_pdf(file_path)
                cleaned_pages = [clean_text(page) for page in raw_text]

                for page_num, content in enumerate(cleaned_pages, 1):
                    all_data.append({
                        "file_name": filename,
                        "page_number": page_num,
                        "cleaned_text": content
                    })
            except Exception as e:
                print(f" Error processing {filename}: {e}")

    df = pd.DataFrame(all_data)
    df.to_csv(output_csv, index=False, encoding='utf-8')
    print(f"\n All PDFs processed and saved to '{output_csv}'")


if __name__ == "__main__":
    input_folder = "/content/temp_extracted_pdfs/data/data"
    output_csv = "processed_all_geopic_reports.csv"
    process_pdf_folder(input_folder, output_csv)

"""pre-processing done
visualization next
"""

!pip install imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.cluster import KMeans
from imblearn.over_sampling import SMOTE
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D, Flatten, Reshape, LSTM, Dropout
from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

# Load CSV
df = pd.read_csv("/content/processed_all_geopic_reports.csv")

# Step 1: Remove missing values
df = df.dropna(subset=["cleaned_text"])

# Step 2: Text Denoising
df["text_length"] = df["cleaned_text"].apply(len)
q_low = df["text_length"].quantile(0.05)
q_hi = df["text_length"].quantile(0.95)
df = df[(df["text_length"] >= q_low) & (df["text_length"] <= q_hi)]

# Step 3: Vectorize with TF-IDF
vectorizer = TfidfVectorizer(max_features=500)
X_tfidf_all = vectorizer.fit_transform(df["cleaned_text"]).toarray()

# Step 4: Clustering to remove noise
kmeans = KMeans(n_clusters=2, random_state=42).fit(X_tfidf_all)
df["cluster"] = kmeans.labels_
majority_cluster = df["cluster"].value_counts().idxmax()
mask = df["cluster"] == majority_cluster
X_tfidf = X_tfidf_all[mask]
df = df[mask].reset_index(drop=True)

# Step 5: Discretization
discretizer = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='uniform')
X_discrete = discretizer.fit_transform(X_tfidf)

# Step 6: Normalization + PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_discrete)

pca = PCA(n_components=50)
X_reduced = pca.fit_transform(X_scaled)

# Step 7: Simulate binary target
y = np.random.randint(0, 2, size=len(X_reduced))

# Step 8: SMOTE - hybrid oversampling
sm = SMOTE(random_state=42)
X_balanced, y_balanced = sm.fit_resample(X_reduced, y)

# Step 9: Train/Test split
X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.2, random_state=42)

# Logistic Regression
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)
acc_log = accuracy_score(y_test, y_pred_log)
f1_log = f1_score(y_test, y_pred_log)

# CNN Model
cnn_model = Sequential([
    Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),
    Conv1D(32, kernel_size=3, activation='relu'),
    MaxPooling1D(2),
    Flatten(),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=1)
acc_cnn = cnn_model.evaluate(X_test, y_test, verbose=0)[1]
y_pred_cnn = (cnn_model.predict(X_test) > 0.5).astype("int32")
f1_cnn = f1_score(y_test, y_pred_cnn)

# RNN Model
rnn_model = Sequential([
    Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),
    LSTM(32),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])
rnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
rnn_model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=1)
acc_rnn = rnn_model.evaluate(X_test, y_test, verbose=0)[1]
y_pred_rnn = (rnn_model.predict(X_test) > 0.5).astype("int32")
f1_rnn = f1_score(y_test, y_pred_rnn)

# Transformer (BERT)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased")

batch_size = 10
all_embeddings = []

for i in range(0, len(df), batch_size):
    batch_texts = df["cleaned_text"].tolist()[i : i + batch_size]
    inputs = tokenizer(batch_texts, return_tensors="tf", truncation=True, padding=True, max_length=128)

    batch_embeddings = bert_model(inputs['input_ids'], inputs['attention_mask'])[1].numpy()
    all_embeddings.append(batch_embeddings)

# Concatenate embeddings from all batches
embeddings = np.concatenate(all_embeddings, axis=0)


y_true = np.random.randint(0, 2, size=len(embeddings))
X_train_tf, X_test_tf, y_train_tf, y_test_tf = train_test_split(embeddings, y_true, test_size=0.2, random_state=42)

transformer_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_tf.shape[1],)),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])
transformer_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
transformer_model.fit(X_train_tf, y_train_tf, epochs=10, batch_size=16, verbose=1)
y_pred_tf = (transformer_model.predict(X_test_tf) > 0.5).astype("int32")
acc_tf = accuracy_score(y_test_tf, y_pred_tf)
f1_tf = f1_score(y_test_tf, y_pred_tf)


# Visualizations
plt.figure(figsize=(8, 4))
sns.histplot(df["text_length"], bins=30, kde=True)
plt.title("Text Length Distribution")
plt.xlabel("Text Length")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(x="cluster", data=df)
plt.title("Cluster Distribution")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.title("Cumulative Explained Variance by PCA Components")
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.heatmap(pd.DataFrame(X_train).corr(), cmap='coolwarm', cbar=True)
plt.title("Correlation Heatmap of Reduced Features")
plt.tight_layout()
plt.show()

# Save Outputs
cleaned_path = "/content/cleaned_text_data.csv"
features_path = "/content/vectorized_features.npy"
df[["file_name", "page_number", "cleaned_text"]].to_csv(cleaned_path, index=False)
np.save(features_path, X_reduced)

# Print Results
print("\nLogistic Regression - Accuracy:", acc_log, "F1 Score:", f1_log)
print("CNN Model - Accuracy:", acc_cnn, "F1 Score:", f1_cnn)
print("RNN Model - Accuracy:", acc_rnn, "F1 Score:", f1_rnn)
print("Transformer Model - Accuracy:", acc_tf, "F1 Score:", f1_tf)
print("\nSaved Cleaned Data:", cleaned_path)
print("Saved Features:", features_path)